services:
  core:
    image: yuzutech/kroki
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - mermaid
      - bpmn
      - excalidraw
      - diagramsnet

  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"

  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"

  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"

  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    expose:
      - "8005"

